language: node_js
node_js:
  - "8.9"

cache:
  directories:
    - "node_modules"

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.37/hugo_0.37_Linux-32bit.deb
  - sudo dpkg -i hugo*.deb
  - rm hugo*.deb

script:
  - hugo

deploy:
  provider: firebase
  token: "${FIREBASE_DEPLOY_TOKEN}"
  project: devfest-baltics-2018
  skip_cleanup: true
  on:
    branch: master
