baseURL = "http://devfest.gdg.lv/"
languageCode = "en-us"
title = "DevFest Baltics 2018"
disableRSS = true
theme = "falconf"

[params]
    description = "DevFest Baltics is the first conference in the Baltics packed with topics about mobile development and carefully crafted for you by GDG Baltics community! All about mobile development, Android and iOS, Mobile Crossplatform tools, UI/UX and prototyping, Internet of Things, VR and AR, bots, AI and more"
    themeColor = "#651fff"
    googleAnalytics = "UA-102993739-2"

[params.social]
    shareImage = "/images/social-share.png"
    twitter = "@devfestbaltics"
    facebook = "devfestbaltics"

[params.sectionTickets]
    enabled = true
    URL = "https://en.xing-events.com/DevFestBaltics2018.html"

[params.sectionTalks]
    enabled = true

[params.sectionCallForPaper]
    enabled = false
    URL = "https://www.papercall.io/devfest-baltics-18"

[params.sectionRetrospectiveVideo]
    enabled = true

[params.sectionWorkshops]
    enabled = true

[params.sectionSchedule]
    enabled = true

[params.sectionPartners]
    enabled = true
